language: java
jdk:
- oraclejdk11
branches:
  only:
  - production
deploy:
  provider: heroku
  app: metisapi
  on:
    branch: production
  api_key:
    secure: rXI/5g7DR6JXEQQBl2xGCSUv9XeUQnuAgmMa2FYfpUozlkVOIeFJgYCSb2Ysee+EIAVZUY7lN0WC140/Sq4I1+L51XMND4ThG5D6T8wRR5mR63z0Q5nEazSrBSWsk4BB32DbX7qEOIRbNJ2SohhCMc05SuoMSab8mqcIDDQ66KcrAcpVDFeAAz6jtCc4S/vc2Ms+b2cBxlgRjLfe7l7owYz+Q3Lev7BH3knmB8oNrxOLuscrQ5YTNBUYDedTNf9UwIzkx6jxkNu4z/C8FycfFKb30nhQrnqZEXYzrwBOBGbMVmc0bFUDRkneB+q1jXfDNIpRb6Dz4JXr7Sooc/JzKLRakXtPUbBlxo+QL7pi70Yf9Q3OJcuVrQbG00ncRXuC26tBEI7N2dSTsejzVxps27W7J98TQSgEfJbqCyKwZ4AmeJCTpAum0IKEZY6FkI2JJrIkV7JWp77iEf5hpzzbJ6umv42P4dOkth2LvxEbH26SOFHM+qxB2rvz2eZZ/rk6zzIZS1ilE2zRICKEe9FPMLwhz3Mw6qyJKoo63e3pspO1SVVGa5OLiQo6B7HHYwrTS0vwTeotuOdmQE2ihj86YTp50m/LK1BNVxPYyCR25m3TEBghr5yGYFJNLtkIjafKf+sc3VbFrm+ODcGPj2F1/kOxd46UW0R7q0MgkPlnZTI=
