language: java
jdk:
- oraclejdk11
branches:
  only:
  - production
deploy:
  provider: heroku
  app: metisapi
  on:
    branch: production
  api_key:
    secure: TLQ42Oib+mNotzMN/8NH/65sx/jBfks/uaAZvzOr1dLJz2WrF64K05fkwV6b/ph3gnEmNXLO34ErVAtV0RLuCZEVE3GEftY6MlMK3yQRJwq2e14VkByVjSPd7uP3fyq/+cwX8oGoXVtAS2r0rOpbgOcUw6+/yVtxIbGSkhbMr9dCSlHDrRVJK5JEVr2O4Utov9Xy+b8yqpA0HXGqxAI8pqzclaarvV5egEHMl7i/ruk+Hmnh/KHuUEHoJpH0xOf8Omscgiopl7kXYbGmB2DB+kHxbZ2esJL1zMFVsjz3xy6EbyF1prD8QtBrLpjt73sdNN+Wan6MRO2IEmimO+QzKFMhbHSneRDpazgG5Q6Eo1rX3yP2M5zZIOZH/wnQMHB2XQJpAKfBJ0A0Rj5xtZZiJPbn0es62PW0Iam8DSqf+ppoTjr05XIqFZyez2Rh2TuS3+gs8uiiqmfLWc9ragt5qnfv0POSuN2od1SK0DEpN3965+zt+DMXAZ/fk19UliY4G/78Za+9JocJXHQwky+tWomf6O+i5M3SsE6RFOAKwKLcfBGsqR4rVumP4+FyHe5tTvdMuv3luHdAHaPElH9XZyX9hZFmob9+YbTKHrwWzDmhy0hk05Du720EUhCKdGx3Mq9wMdSsWUcXwWdDa13annUTIXSNHLI0SQU6CUzsevc=
