language: java
jdk:
- oraclejdk11
branches:
  only:
  - production
deploy:
  provider: heroku
  app: metisapi
  on:
    branch: production
  api_key:
    secure: pdSg/4XYdqUi8jlzhMPlYvjsV9g5UrArIXUbFJnHG/htItyjC4QEhAkls1+SGnKYEp9JjrbfaVTCZnJI/XxIRSqfrrSPxJha9evq4W28rGJVWv2s4miPgfBF9RkEV6b2ntMat8d4jjsbdZUL7zi0D0BvQ30pc6hFkKJHTLoGF77/Wv0n1XctJ9bt2hqMlyrSiv0gURvYkjjHrloviVPJ7hL/lyeolZs0hu2OVMAG7Zwwr14NnAGUqwBkLuKu3wD2UJTEt5pqvRxghQtZHoR828UCZRfQovx7OrsC6T9LJQIAv80eyIELayie0y70sUgbadt2nUbtalpkgzuSZatqtUM0YqNtIK3hjQfVfPwGz+2IR9hCFj5Hb83Ud4a6jnE1wRrNQkSw1jM0kVozadujyX6Xvzd47JAfzkDK9C25wV7Lx++wl5XhS3bj4+PD/zd3CCj7JMzDTNylDeiDC6Dj0xXJi5k3UOtQgAnneslRbd3dxaWeqGGPOmES97s3W3LFvmWSjhxtsokbEdL/gczFiHsKnryvykJgpJgcL5Qz1UKNp4UdUYiRHi2hWG3HvbZM2wVGKwm2W2B62J+2Ax9T++OHL4CbZ+Zprt7TQU8TxBx0uWMsVwON+0/yi9y31krXb9OnHG5JQCMDvKgVd3qZ43Vnh681UPb5LLuxz55cdAw=
